# Generated by Django 4.0.6 on 2022-07-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonic_server_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='username2',
        ),
    ]
